name: dependabot_auto_merge
on: pull_request

jobs:
  automerge:
    runs-on: ubuntu-latest
    environment: Dependabot
    steps:
    - run: echo token is ${{ secrets.TEST }} == ${{ secrets.GITHUB_TOKEN }} 
    - uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        github-token: ${{ secrets.TEST }}
