name: dependabot
on: [push, pull_request]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.6.2
        with: 
           approve-only: true
           use-github-auto-merge: true
           github-token: ${{ secrets.TOKEN }}
           target: windows
 
