name: dependabot_auto_merge
on: pull_request

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - name: testing secrets
      run : echo ${{ secrets.DEP }}
    - uses: actions/checkout@v2
    - uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        github-token: ${{ secrets.DEP }}
