name: release to github packages
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    # defaults:
    #   run:
    #     shell: pwsh
    #     working-directory: ./lib
    permissions:
      contents: read
      packages: write

    steps:

        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '19'
            distribution: 'temurin'

        
        - name: build and test publish
          uses: gradle/gradle-build-action@v2.4.0
          with: 
            gradle-version: current
            arguments: publishAllPublicationsToTestRepository
            build-root-directory: ./lib
        
        - name: see the tree of repo
          run: tree lib/build/maven-repo

        - name: Publish to GitHub Packages
          uses: gradle/gradle-build-action@v2.4.0
          with:
            build-root-directory: ./lib
            arguments: publish
          env:
            GITHUB_ACTOR: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.PACKAGE }}