name: release to github packages
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    # defaults:
    #   run:
    #     shell: pwsh
    #     working-directory: ./lib
    permissions:
      contents: read
      packages: write

    steps:

        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 19
          uses: actions/setup-java@v3
          with:
            java-version: '19'
            distribution: 'temurin'
  
        - name: publish to github packages
          uses: gradle/gradle-build-action@v2.4.0
          with: 
            gradle-version: current
            arguments: publish
            build-root-directory: ./lib
          env:
            GITHUB_ACTOR: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.TOKEN }}